variable "vpc_cidr" {}
variable "vpc_name" {}
variable "env" {}
variable "IGW_name" {}
variable "subnet_cidr_1" {}
variable "subnet_cidr_2" {}
variable "subnet_name_1" {}
variable "subnet_name_2" {}
variable "route" {}
variable "az1" {}
variable "az2" {}
variable "subnet_cidr_3" {}
variable "subnet_name_3" {}
variable "vpc_cidr_1" {}
variable "vpc_name_1" {}
